In [4]:
from google.colab import files
uploaded = files.upload()

Saving zomato.csv to zomato.csv

In [35]:
#importing data set and displaying
import pandas as pd
df = pd.read_csv('zomato.csv')
display(df.head())

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur

In [36]:
#checking for missing values
display(df.isnull().sum())

Unnamed: 0.1              0
Unnamed: 0                0
restaurant name           0
restaurant type           0
rate (out of 5)          68
num of ratings            0
avg cost (two people)    57
online_order              0
table booking             0
cuisines type             0
area                      0
local address             0
dtype: int64

In [37]:
print(len(df))

#this is done to see if its ok to drop 68 rows.

7105

In [38]:
df = df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])
df = df.rename(columns={'rate (out of 5)': 'rate','avg cost (two people)': 'avg cost'})
display(df.head())
#renaming the columns

,restaurant name,restaurant type,rate,num of ratings,avg cost,online_order,table booking,cuisines type,area,local address
0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur

In [39]:
df = df.dropna()
print(len(df))
display(df.isnull().sum())
#68 rows for rate column and 57 rows for avg cost column were missing values. so at max about 125 rows would be missing data. which is less compared to the total number of
# rows which was 7105. so i decided dropna would be best because its just negligible amount of rows.

6984

restaurant name    0
restaurant type    0
rate               0
num of ratings     0
avg cost           0
online_order       0
table booking      0
cuisines type      0
area               0
local address      0
dtype: int64

In [40]:
df = df.drop_duplicates()
print(len(df))
#no duplicate rows.

6984

In [41]:
df['restaurant name'] = df['restaurant name'].str.strip()
df['area'] = df['area'].str.strip().str.title()
df['local address'] = df['local address'].str.strip().str.title()
df['cuisines type'] = df['cuisines type'].str.strip().str.title()

In [42]:
display(df.info())
#checking for incorrect data types

<class 'pandas.core.frame.DataFrame'>
Index: 6984 entries, 0 to 7104
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   restaurant name  6984 non-null   object
 1   restaurant type  6984 non-null   object
 2   rate             6984 non-null   float64
 3   num of ratings   6984 non-null   int64
 4   avg cost         6984 non-null   float64
 5   online_order     6984 non-null   object
 6   table booking    6984 non-null   object
 7   cuisines type    6984 non-null   object
 8   area             6984 non-null   object
 9   local address    6984 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 600.2+ KB

None

In [43]:
def rating_category(rate):
    if rate < 3:
        return "Poor"
    elif rate < 3.5:
        return "Average"
    elif rate < 4:
        return "Good"
    else:
        return "Very nice"

df['rating_category'] = df['rate'].apply(rating_category)
#adding this column helps in understanding customer's perception about restaurants.

In [44]:
display(df.head())

,restaurant name,restaurant type,rate,num of ratings,avg cost,online_order,table booking,cuisines type,area,local address,rating_category
0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur,Average
1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",Hsr,Good
2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road,Good
3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli,Poor
4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"Bbq, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur,Poor

In [45]:
df.to_csv('cleaned_restaurants.csv', index=False)